import { Header } from "./_components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Footer } from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={"fixed left-0 top-0 z-10 w-full "}>
          <Header></Header>
        </div>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
