name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: shiron-dev
  server-deploy:
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
